{% set name = "httpx" %}
{% set version = "0.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f99c15d33642d38bce8405df088c1c4cfd940284b4290cacbfb02e64f4877c6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - anyio >=3.0.0  # [py==37]
    - async_generator  # [py<37]
    - certifi
    - httpcore >=0.13.3,<0.14.0,!=pyhd8ed1ab_0
    - idna
    - python
    - rfc3986 >=1.3,<2
    - sniffio
    - typing-extensions  # [py<37]

test:
  imports:
    - httpx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  doc_url: https://www.encode.io/httpx/
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
    - thewchan
