{% set name = "httpx" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92ecd2c00c688b529eda11cedb15161eaf02dee9116712f621c70d9a40b2cdd0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == 'pypy' and py==37]

requirements:
  host:
    - python
    - pip
  run:
    - anyio ==3.*  # [py==37]
    - async_generator  # [py<37]
    - certifi
    - httpcore >=0.13.3,<0.14.0
    - idna
    - python
    - rfc3986 >=1.3,<2
    - sniffio
    - charset_normalizer

test:
  imports:
    - httpx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  doc_url: https://www.encode.io/httpx/
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
    - thewchan
